"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setup import config
from setuptools import setup

py2app_config = dict(
    app=['hatta.py'],
    options={'py2app': {
        'argv_emulation': True,
        'includes': ['werkzeug.contrib.wrappers'],
        'iconfile': \
            '/Users/cezarykrzyzanowski/Downloads/Hatta-Wiki-1.3.1/hatta.icns',
    }},
    setup_requires=['py2app'],
)
config.update(py2app_config)

setup(**config)
