# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/HattaError.ui'
#
# Created: Fri Jul 16 19:56:19 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ErrorDialog(object):
    def setupUi(self, ErrorDialog):
        ErrorDialog.setObjectName("ErrorDialog")
        ErrorDialog.resize(400, 302)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ErrorDialog.sizePolicy().hasHeightForWidth())
        ErrorDialog.setSizePolicy(sizePolicy)
        ErrorDialog.setMinimumSize(QtCore.QSize(400, 300))
        ErrorDialog.setSizeIncrement(QtCore.QSize(0, 0))
        ErrorDialog.setBaseSize(QtCore.QSize(400, 300))
        ErrorDialog.setAutoFillBackground(True)
        ErrorDialog.setSizeGripEnabled(False)
        ErrorDialog.setModal(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ErrorDialog)
        self.verticalLayout_2.setSpacing(24)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.error_icon = QtGui.QLabel(ErrorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_icon.sizePolicy().hasHeightForWidth())
        self.error_icon.setSizePolicy(sizePolicy)
        self.error_icon.setMinimumSize(QtCore.QSize(64, 64))
        self.error_icon.setBaseSize(QtCore.QSize(64, 64))
        self.error_icon.setText("")
        self.error_icon.setScaledContents(False)
        self.error_icon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.error_icon.setObjectName("error_icon")
        self.horizontalLayout_2.addWidget(self.error_icon)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error_title = QtGui.QLabel(ErrorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_title.sizePolicy().hasHeightForWidth())
        self.error_title.setSizePolicy(sizePolicy)
        self.error_title.setTextFormat(QtCore.Qt.RichText)
        self.error_title.setScaledContents(False)
        self.error_title.setWordWrap(True)
        self.error_title.setMargin(0)
        self.error_title.setObjectName("error_title")
        self.verticalLayout.addWidget(self.error_title)
        self.error_descriptions = QtGui.QLabel(ErrorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_descriptions.sizePolicy().hasHeightForWidth())
        self.error_descriptions.setSizePolicy(sizePolicy)
        self.error_descriptions.setScaledContents(True)
        self.error_descriptions.setWordWrap(True)
        self.error_descriptions.setMargin(0)
        self.error_descriptions.setObjectName("error_descriptions")
        self.verticalLayout.addWidget(self.error_descriptions)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.error_traceback = QtGui.QPlainTextEdit(ErrorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_traceback.sizePolicy().hasHeightForWidth())
        self.error_traceback.setSizePolicy(sizePolicy)
        self.error_traceback.setMinimumSize(QtCore.QSize(0, 40))
        self.error_traceback.setUndoRedoEnabled(False)
        self.error_traceback.setReadOnly(True)
        self.error_traceback.setObjectName("error_traceback")
        self.verticalLayout_2.addWidget(self.error_traceback)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.details_button = QtGui.QPushButton(ErrorDialog)
        self.details_button.setCheckable(True)
        self.details_button.setChecked(False)
        self.details_button.setObjectName("details_button")
        self.horizontalLayout.addWidget(self.details_button)
        self.buttonBox = QtGui.QDialogButtonBox(ErrorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(ErrorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ErrorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ErrorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ErrorDialog)

    def retranslateUi(self, ErrorDialog):
        ErrorDialog.setWindowTitle(QtGui.QApplication.translate("ErrorDialog", "Error Report", None, QtGui.QApplication.UnicodeUTF8))
        self.error_title.setText(QtGui.QApplication.translate("ErrorDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">An error occured. Send a bug report?</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.error_descriptions.setText(QtGui.QApplication.translate("ErrorDialog", "We\'re sorry, but unfortunately Hatta has encountered some difficulties. Would you like to send us a bug report, so that we might fix the issue?", None, QtGui.QApplication.UnicodeUTF8))
        self.error_traceback.setPlainText(QtGui.QApplication.translate("ErrorDialog", "Traceback here.", None, QtGui.QApplication.UnicodeUTF8))
        self.details_button.setText(QtGui.QApplication.translate("ErrorDialog", "&Details", None, QtGui.QApplication.UnicodeUTF8))
